apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  activeDeadlineSeconds: 10
  template:
    spec:
      containers:
        - name: hello
          image: busybox
          command: ["sleep", "60"]
      restartPolicy: Never

      


