apiVersion: v1
kind: Pod
metadata:
  name: print-greeting-secrets
spec:
  containers:
  - name: env-print-demo
    image: bash
    env:
    - name: USERNAME
      valueFrom:
            secretKeyRef:
              name: creds-secret
              key: username
    - name: PWD
      valueFrom:
            secretKeyRef:
              name: creds-secret
              key: password
    command: ["echo"]
    args: ["$(USERNAME) $(PWD)"]
  restartPolicy: Never

  
  