apiVersion: v1
kind: Pod
metadata:
  name: print-greeting-configmap
spec:
  containers:
  - name: env-print-demo
    image: bash
    env:
    - name: GREETING
      valueFrom:
            configMapKeyRef:
              name: example-config
              key: GREETING
    - name: HONORIFIC
      valueFrom:
            configMapKeyRef:
              name: example-config
              key: HONORIFIC
    - name: NAME
      valueFrom:
            configMapKeyRef:
              name: example-config
              key: NAME
    command: ["echo"]
    args: ["$(GREETING) $(HONORIFIC) $(NAME)"]
  restartPolicy: Never

  